### ISSUE TITLE
The project is not loading up correctly.

### ISSUE THREAD

**Issue by coderabsolute** [SpoonX/aurelia-api#189]
Not sure whether this is related to the latest release but can someone please help looking at this error and identify what is wrong?

`bluebird.min.js:31 Unhandled rejection (SystemJS) exports is not defined
    ReferenceError: exports is not defined
        at eval (http://localhost:9000/jspm_packages/npm/aurelia-api@3.1.0/aurelia-api.js:5:1)
        at eval (http://localhost:9000/jspm_packages/npm/aurelia-api@3.1.0/aurelia-api.js:249:3)
        at eval (<anonymous>)
        at r (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:33:7722)
        at i._settlePromiseFromHandler (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:32:13044)
        at i._settlePromise (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:32:13847)
        at i._settlePromise0 (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:32:14548)
        at i._settlePromises (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:32:15878)
        at r._drainQueue (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:31:3148)
        at r._drainQueues (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:31:3209)
        at drainQueues (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:31:1238)
    Evaluating http://localhost:9000/jspm_packages/npm/aurelia-api@3.1.0/aurelia-api.js
    Error loading http://localhost:9000/jspm_packages/npm/aurelia-api@3.1.0/aurelia-api.js as "npm:aurelia-api@3.1.0/aurelia-api" from http://localhost:9000/jspm_packages/npm/aurelia-api@3.1.0.js`

**Comment by RWOverdijk** [comment]
I have never seen this error before in my life. What version are you using?

**Comment by TimBailey-pnk** [comment]
Same issue for me, just updated this morning to v3.1 of aurelia-api.

`
Error: (SystemJS) exports is not defined
	ReferenceError: exports is not defined
	    at eval (http://localhost:9000/jspm_packages/npm/aurelia-api@3.1.0/aurelia-api.js:5:1)
	    at eval (http://localhost:9000/jspm_packages/npm/aurelia-api@3.1.0/aurelia-api.js:249:3)
	    at eval (<anonymous>)
	Evaluating http://localhost:9000/jspm_packages/npm/aurelia-api@3.1.0/aurelia-api.js
	Error loading http://localhost:9000/jspm_packages/npm/aurelia-api@3.1.0/aurelia-api.js as "npm:aurelia-api@3.1.0/aurelia-api" from http://localhost:9000/jspm_packages/npm/aurelia-api@3.1.0.js
	    at eval (http://localhost:9000/jspm_packages/npm/aurelia-api@3.1.0/aurelia-api.js:5:1)
	    at eval (http://localhost:9000/jspm_packages/npm/aurelia-api@3.1.0/aurelia-api.js:249:3)
	    at eval (<anonymous>)
	Evaluating http://localhost:9000/jspm_packages/npm/aurelia-api@3.1.0/aurelia-api.js
	Error loading http://localhost:9000/jspm_packages/npm/aurelia-api@3.1.0/aurelia-api.js as "npm:aurelia-api@3.1.0/aurelia-api" from http://localhost:9000/jspm_packages/npm/aurelia-api@3.1.0.js
`

**Comment by gregoryagu** [comment]
I also just updated to V.1 and get the same exact error.  I think the issue is that it was compiled to the AMD format, instead of the systemjs format.

All the Aurelia libs I have seen look like this:

```
define(['exports', './aurelia-bootstrapper'], function (exports, _aureliaBootstrapper) {
  'use strict';

  Object.defineProperty(exports, "__esModule", {
    value: true
  });
  Object.keys(_aureliaBootstrapper).forEach(function (key) {
    if (key === "default" || key === "__esModule") return;
    Object.defineProperty(exports, key, {
      enumerable: true,
      get: function () {
        return _aureliaBootstrapper[key];
      }
    });
  });
});

```

Aurelia api index.js looks like this:

```
/* */ 
"format amd";
'use strict';

exports.__esModule = true;

var _aureliaApi = require('./aurelia-api');

Object.keys(_aureliaApi).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function get() {
      return _aureliaApi[key];
    }
  });
});
```

In other words, I think the module type is incorrect.

**Comment by PWKad** [comment]
Looks like the dist/amd files are actually coming through as common.js or something.

**Comment by RWOverdijk** [comment]
@gregoryagu @coderabsolute Could you try updating?

**Comment by gregoryagu** [comment]
Success.  I updated to 3.1.1 and no issues.

**Comment by TimBailey-pnk** [comment]
3.1.1 Fixes it for me too.  Thanks for sorting.

**Comment by coderabsolute** [comment]
@RWOverdijk It's really good to see my app again, for a record I just needed to update the Jspm.

`jspm update`
